config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :posts do
    resources :comments
  end
  get "logout" => "sessions#destroy"
  get "login" => "sessions#new"
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum:5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def require_login
    unless current_user
      redirect_to login_url, notice: "ログインして下さい！"
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :require_login, only:[:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :require_login, only:[:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.all
    render :index
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post

    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to post_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = login(params[:email], params[:password], params[:remenber_me])
    if user
      redirect_back_or_to root_url, :notice => "logged in!"
    else
      render :new
      flash.now.alert = "Email or password was invalid"
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.erb
<h1>Hello,Rails!</h1>
<%= link_to "私のブログ", posts_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>コメンター：</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>コメント：</strong>
  <%= simple_format comment.body %>
</p>

<p>
  <%= link_to 'コメント削除', [comment.post, comment],
                             method: :delete, data: { confirm: '削除しますか？' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for( [@post, @post.comments.build] ) do |f| %>
  <p>
    <%= f.label :commenter, "コメンター" %><br/>
    <%= f.text_field :commenter %>
  </p>

  <p>
    <%= f.label :body, "コメント" %><br/>
    <%= f.text_area :body, cols: 60, rows: 8 %>
    <div class="hint">入力文字数:<span id="char_num">0</span></div>
  </p>

  <p>
    <%= f.submit "コメント投稿" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ja="ja">
<head>
  <meta charset="utf-8" />
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
<div id="wrap">

  <header id="header">
    <div class="inner">
      <h1 id="logo"><%= link_to "Sample My Blog", root_path %></h1>
      <p id="catchcopy">Description or something ....</p>
    </div>
  </header>

  <body class="<%= params[:controller] %>">
    <div id ="container">
      <div class ="user_nav">
        <% if current_user %>
          Logged in as <%= current_user.email %>,
          <%= link_to 'Log out', logout_path %>
        <% else %>
          <%= link_to 'Log in', login_path %>
        <% end %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
    </div>
  <div id="main">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーが発生したため保存ができませんでした。</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text, "内容" %><br>
    <%= f.text_area :text, cols: 60, rows: 8 %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>投稿を更新</h1>

<%= render 'form' %>

<%= link_to "戻る", posts_path %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>

<table>
  <tr>
    <th>タイトル</th>
    <th>本文</th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= link_to "詳細", post %></td>
      <td><%= link_to "編集", edit_post_path(post) %></td>
      <td><%= link_to "削除", post_path(post),
                             method: :delete, data: { confirm: "削除しますか？" } %>
    </tr>
  <% end %>
</table>

<%= link_to "新しい投稿", new_post_path %>

app/views/posts/new.html.erb
<h1>新しい投稿</h1>

<%= render 'form' %>

<%= link_to "戻る", posts_path %>

app/views/posts/show.html.erb
<h1>投稿内容</h1>
<div class="post_info">
<p>
  <strong>タイトル；</strong>
  <%= @post.title %>
</p>

<p>
  <strong>本文：</strong>
  <%= simple_format @post.text %>
</p>
</div>

<h2>コメント欄</h2>
<% @post.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>

<h2>コメントを追加</h2>
<%= render 'comments/form' %>

<%= link_to "戻る", posts_path %>
<%= link_to "編集", edit_post_path(@post) %>

app/views/users/new.html.erb
<h1>sign up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages" %>
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages do |message| %>
          <li><%= message %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confiemation %>
  </div>

  <div class="actions"><%= f.submit %></div>

<% end %>